#!/bin/bash
# Install Node.js on macOS - Easy Guide

echo "🔧 Node.js Installation for CollectEVM"
echo "======================================="
echo ""
echo "I'll help you install Node.js step by step!"
echo ""

# Check if Node.js is already installed
if command -v node &> /dev/null; then
    echo "✅ Node.js is already installed!"
    echo "   Version: $(node --version)"
    echo "   npm version: $(npm --version)"
    echo ""
    echo "You're ready to deploy! Run:"
    echo "   cd /Users/phillipyon/Downloads/CollectEVM-master"
    echo "   ./final-deploy.sh"
    exit 0
fi

echo "❌ Node.js not found. Let's install it!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OPTION 1: Download Installer (Easiest - Recommended)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open this URL in your browser:"
echo "   https://nodejs.org/en/download/"
echo ""
echo "2. Download 'macOS Installer' (LTS version)"
echo ""
echo "3. Run the .pkg file and follow the installer"
echo ""
echo "4. Restart your terminal"
echo ""
echo "5. Run this script again to verify"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OPTION 2: Using Homebrew (If you have it)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If you have Homebrew installed, run:"
echo "   brew install node"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "After Installation"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Close and reopen your terminal"
echo "2. Verify installation:"
echo "   node --version"
echo "   npm --version"
echo ""
echo "3. Deploy your app:"
echo "   cd /Users/phillipyon/Downloads/CollectEVM-master"
echo "   ./final-deploy.sh"
echo "   vercel"
echo ""
echo "🎉 Your site will be live in 3 minutes!"
echo ""

